{{ $channel_version := (split "-" .Values.cluster_logging_operator_channel)._1 }}
{{- if le $channel_version "5.9" }}
---
apiVersion: logging.openshift.io/v1
kind: ClusterLogForwarder
metadata:
  name: instance
  namespace: openshift-logging
  annotations:
    argocd.argoproj.io/sync-wave: "056"
    argocd.argoproj.io/sync-options: "SkipDryRunOnMissingResource=true,Validate=false"
{{- if .Values.custom_labels }}
  labels:
{{ .Values.custom_labels | toYaml | indent 4 }}
{{- end }}
spec:
  inputs:
    - application:
        excludes:
          - container: auth-store
            namespace: mas-*-iot
          - container: api-authorization
            namespace: mas-*-iot
          - container: rest-v2-sync-scheduler
            namespace: mas-*-monitor
      name: application-logs
      type: application
  filters:
    - drop:
        - test:
            - field: .level
              matches: info|Info|INFO|DEBUG|Debug|debug
      name: noise
      type: drop
    - kubeAPIAudit:
        omitStages: []
        rules:
          - level: Metadata
      name: sos-policy
      type: kubeAPIAudit
  outputs:
    - name: cloudwatch-1
      type: cloudwatch
      secret:
        name: cloudwatch
      tuning:
        compression: zstd
      cloudwatch:
        groupBy: logType
        groupPrefix: '{{ .Values.cluster_id }}'
        region: '{{ .Values.region_id }}'
{{- if .Values.use_syslog_forwarder }}
    - name: rsyslog-local
      type: syslog
      url: 'tcp://syslog-forwarder:9200'
      syslog:
        appName: myapp
        facility: user
        msgID: mymsg
        procID: myproc
        rfc: RFC5424
        severity: informational
{{- end }}
  pipelines:
    - name: app-logs
      detectMultilineErrors: true
      filterRefs:
        - noise
      inputRefs:
        - application-logs
      outputRefs:
        - cloudwatch-1
    - name: infra-logs
      detectMultilineErrors: true
      inputRefs:
        - infrastructure
      outputRefs:
        - cloudwatch-1
    - name: audit-logs
      filterRefs:
         - sos-policy
      inputRefs:
        - audit
      outputRefs:
        - cloudwatch-1
{{- if .Values.use_syslog_forwarder }}
        - rsyslog-local
{{- end }}

{{- end }}


{{- if ge $channel_version "6.0" }}
---
apiVersion: observability.openshift.io/v1
kind: ClusterLogForwarder
metadata:
  name: instance
  namespace: openshift-logging
  annotations:
    argocd.argoproj.io/sync-options: 'SkipDryRunOnMissingResource=true,Validate=false'
    argocd.argoproj.io/sync-wave: '056'
{{- if .Values.custom_labels }}
  labels:
{{ .Values.custom_labels | toYaml | indent 4 }}
{{- end }}
spec:
  inputs:
    - application:
        excludes:
          - container: auth-store
            namespace: mas-*-iot
          - container: api-authorization
            namespace: mas-*-iot
          - container: rest-v2-sync-scheduler
            namespace: mas-*-monitor
      name: application-logs
      type: application
  serviceAccount:
    name: collector
  filters:
    - drop:
        - test:
            - field: .level
              matches: info|Info|INFO|DEBUG|Debug|debug
      name: noise
      type: drop
    - kubeAPIAudit:
        omitStages: []
        rules:
          - level: Metadata
      name: sos-policy
      type: kubeAPIAudit
    - prune:
        notIn:
          - .message
          - .log_type
          - .log_source
          - .kubernetes.namespace_name
          - .kubernetes.pod_name
          - .kubernetes.container_name
          - .kubernetes.labels.app
          - .kubernetes.labels.mas_ibm_com_instanceId
          - .kubernetes.container_image
      name: prune-fields
      type: prune
  outputs:
    - name: cloudwatch-1
      type: cloudwatch
      cloudwatch:
        tuning:
          compression: zstd
        authentication:
          type: awsAccessKey
          awsAccessKey:
            keyId:
              secretName: cloudwatch
              key: aws_access_key_id
            keySecret:
              secretName: cloudwatch
              key: aws_secret_access_key
        groupName: '{{ .Values.cluster_id }}_{.log_type||"unknown"}'
        region: '{{ .Values.region_id }}'
{{- if .Values.use_syslog_forwarder }}
    - name: rsyslog-local
      type: syslog
      syslog:
        url: 'tcp://syslog-forwarder:9200'
        appName: myapp
        facility: user
        msgId: mymsg
        procId: myproc
        rfc: RFC5424
        severity: informational
{{- end }}
  pipelines:
    - name: app-logs
      filterRefs:
        - noise
        - prune-fields
      inputRefs:
        - application-logs
      outputRefs:
        - cloudwatch-1
    - name: infra-logs
      inputRefs:
        - infrastructure
      outputRefs:
        - cloudwatch-1
    - name: audit-logs
      filterRefs:
         - sos-policy
      inputRefs:
        - audit
      outputRefs:
        - cloudwatch-1
{{- if .Values.use_syslog_forwarder }}
        - rsyslog-local
{{- end }}

{{- end }}